import turtle
t = turtle.Turtle()
turtle.bgcolor("blue")
t.up()
t.down()
t.color("red")
t.begin_fill()
t.fillcolor("yellow")
turtle.colormode("red")
t.circle(100, steps=12)
t.end_fill()
t.up()
t.backward(200)
t.hideturtle()
t.home()
turtle.done()